name: Skip tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!react-app/**'
      - 'react-app/public/**'
      - 'react-app/src/assets/**'

jobs:
  Test:
    name: Vite test
    runs-on: ubuntu-latest
    steps:
      - run: echo test skipped.